### ISSUE TITLE
 sqlite3.OperationalError: database is locked error

### ISSUE THREAD

**Issue by damntourists** [nbr23/youtube-dl-server#10]
Hi there,

I'm attempting to run this in portainer and getting the following error whenever starting the container:

```
Outdated jbos table, cleaning up and recreating
Traceback (most recent call last):
  File "./youtube-dl-server.py", line 114, in <module>
    JobsDB.init_db()
  File "/usr/src/app/ydl_server/logdb.py", line 72, in init_db
    cursor.execute("CREATE TABLE if not exists jobs \
sqlite3.OperationalError: database is locked
```

Any ideas?

**Comment by nbr23** [comment]
Hi @damntourists 
This might be linked to rights issue on the sqlite db file? Can you double check that the user has write access to the db location?

Thanks,

**Comment by damntourists** [comment]
That seems to be the issue! Thanks!

**Comment by damntourists** [comment]
Hi there, sorry to revive a previously closed ticket -- I think I've figured out why this was causing errors and figured I'd let you know in case you weren't aware. 

I had mounted a volume pointing to my network SMB 2 share which is mounted on ubuntu using cifs. It appears that sqlite does not behave well using NFS mounts, which is why I have been encountering this error.

```
2.1. Filesystems with broken or missing lock implementations

SQLite depends on the underlying filesystem to do locking as the documentation says it will. But some filesystems contain bugs in their locking logic such that the locks do not always behave as advertised. This is especially true of network filesystems and NFS in particular. If SQLite is used on a filesystem where the locking primitives contain bugs, and if two or more threads or processes try to access the same database at the same time, then database corruption might result.
```
source: https://sqlite.org/howtocorrupt.html

Is it possible to write the downloads out to a different directory instead of keeping them along side the db files?

**Comment by nbr23** [comment]
Hi @damntourists,

If you edit https://github.com/nbr23/youtube-dl-server/blob/master/config.yml and update the following line, you can have the sqlite db stored at another location:
`  metadata_db_path: '/youtube-dl/.ydl-metadata.db' # Path to metadata DB`

It could make sense to have it point for example to:
`  metadata_db_path: '/app_config/.ydl-metadata.db'`

Let me know how that works out for you :)

Cheers!

**Comment by damntourists** [comment]
Ok, that seems to have worked! This is what I wound up using:
```
---
version: "2.1"
services:
  youtube-dl:
    image: "nbr23/youtube-dl-server:latest"
    container_name: youtube-dl
    environment:
      - YDL_CONFIG_PATH=/usr/src/app/config.yml
    volumes:
      - /mnt/nas/sync/youtube-dl:/youtube-dl
      - /mnt/nas/projects/homelab/configurations/youtube-dl-server/config.yml:/usr/src/app/config.yml:ro
    ports:
      - 8888:8080
    restart: always
```

I added in the environment variable because it appears it was defaulting to `/app_config/config.yml`.

Thanks again for your help! It's working perfectly now!
