### ISSUE TITLE
[QUESTION] MP3 Audio quality

### ISSUE THREAD

**Issue by bluebackdev** [nbr23/youtube-dl-server#109]
Firstly, great piece of software!

I have a question on how the MP3 download quality works.
I was doing some reading and it looks like the best approach to get the best quality MP3 is like this:
```bash
youtube-dl -f "bestaudio/best" -ciw -o "%(title)s.%(ext)s" -v --extract-audio --audio-quality 0 --audio-format mp3  https://www.youtube.com/watch?v=c29tZVZpZGVvUGxheWxpc3RQYXJ0
```
_ref: https://stackoverflow.com/questions/49804874/download-the-best-quality-audio-file-with-youtube-dl_

Is this how your library does it, or does it do it directly as MP3, because if it's directly as MP3 then it might not be the best possible quality compared to downloading it first _(in Opus format I believe)_ and then converting it to MP3 with `--audio-quality 0`

---

Also a suggestion to please change line `6` in `config.yml` to:
```yml
output_playlist: '/youtube-dl/%(playlist_title)s [%(playlist_id)s]/%(title)s.%(ext)s' # Playlist output directory template
```
to give noobs a bit of guidance (I spent about 2hours trying to figure out why it wasn't downloading playlist files into a subdirectory as I thought `%(title)s` was for the Playlist title but in fact it was `playlist_title`

Thanks in advance :)

**Comment by bluebackdev** [comment]
```
[debug] Command-line config: ['--output', '/youtube-dl/%(playlist_title)s [%(playlist_uploader)s] [%(playlist_uploader_id)s] [%(playlist_id)s]/%(title)s.%(ext)s', '--cache-dir', '/youtube-dl/.cache', '--ignore-errors', '--geo-bypass', '--embed-thumbnail', '--add-metadata', '--verbose', '--extract-audio', '--audio-format', 'mp3',
```

that's what the command is currently like, I don't see no `--audio-quality 0` 

My config is:
```yaml
ydl_server:   # youtube-dl-server specific settings
  port: 8080      # Port youtube-dl-server should listen on
  host: 0.0.0.0   # IP youtube-dl-server should bind to
  debug: False    # Enable/Disable debug mode
  metadata_db_path: '/youtube-dl/.ydl-metadata.db' # Path to metadata DB
  output_playlist: '/youtube-dl/%(playlist_title)s [%(playlist_uploader)s] [%(playlist_uploader_id)s] [%(playlist_id)s]/%(title)s.%(ext)s' # Playlist output directory template
  #max_log_entries: 100 # Maximum number of job log history to keep
  #forwarded_allow_ips: None # uvicorn Comma seperated list of IPs to trust with proxy headers.
  #proxy_headers: True # uvicorn flag Enable/Disable X-Forwarded-Proto, X-Forwarded-For, X-Forwarded-Port to populate remote address info.
  default_format: audio/mp3 # Default format selection
  #download_workers_count: 2 # Number of download worker threads
 
ydl_options:  # youtube-dl options
  output: '/youtube-dl/%(title)s.%(ext)s' # output directory template
  cache-dir: '/youtube-dl/.cache' # youtube-dl cache directory
  ignore-errors: True # instruct youtube-dl to skip errors
  geo-bypass: True
  write-thumbnail: True
  embed-thumbnail: True
  add-metadata: True
  verbose: True
```

Am I perhaps missing something like:
```yaml
  format:  bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/best[ext=mp4]/best 
```

Please can you guide me on what I am missing and what it should be, thanks

**Comment by nbr23** [comment]
Hi @bluebackdev thx for the issue! I fixed the playlist thing in the config, good call!

For the parameters you want, you can just list them up like you do in the command line:

from:
```
youtube-dl -f "bestaudio/best" --extract-audio --audio-quality 0 --audio-format mp3  https://www.youtube.com/watch?v=c29tZVZpZGVvUGxheWxpc3RQYXJ0
```

to

```yaml
      ydl_options:
        format: bestaudio/best
        audio-quality: 0
        extract-audio: True
        audio-format: mp3
```

Btw, you can now use profiles (which I'm going to write about in the README ASAP!) by declaring them the following way in your config.yml:

```yaml

profiles:
  podcast:
      name: 'Fantastic audio quality'
      ydl_options:
        format: bestaudio/best
        geo-bypass: True
        write-thumbnail: True
        embed-thumbnail: True
        add-metadata: True
        verbose: True
        audio-quality: 0
        extract-audio: True
        audio-format: mp3
```

Which will then show up in the ui as such:
<img width="519" alt="image" src="https://github.com/nbr23/youtube-dl-server/assets/1313493/a084cee0-5fb8-4d31-9b88-d23914baa34c">

And with the example above, the command is the following, which I think achieves what you want:

```
yt-dlp-1  | ['yt-dlp', '--output', '/youtube-dl/%(title)s [%(id)s].%(ext)s', '--cache-dir', '/youtube-dl/.cache', '--ignore-errors', '--age-limit', '6', '--format', 'bestaudio/best', '--geo-bypass', '--write-thumbnail', '--embed-thumbnail', '--add-metadata', '--verbose', '--audio-quality', '0', '--extract-audio', '--audio-format', 'mp3', '--', 'https://www.youtube.com/watch?v=BLAH']
```

Hope this helps, let me know if not!
