### ISSUE TITLE
Regression: Audio not being downloaded anymore

### ISSUE THREAD

**Issue by Fribb** [nbr23/youtube-dl-server#114]
My Server updated this night to the latest version which seems to have a regression regarding the Audio being downloaded.

I noticed that the downloaded files only have a Video track but no Audio Track.
Using the `nbr23/youtube-dl-server:0dfe6e9-yt-dlp` docker tag everything works fine, the downloaded video contains both audio and video tracks
Using the next tag `nbr23/youtube-dl-server:9bd46ab-yt-dlp`, Audio tracks are not being downloaded anymore.

I would assume that this has something to do with the 9bd46ab commit that there is something going wrong or that I now missing in my configuration?

My Config:
```
ydl_server:
  port: 8080
  host: 0.0.0.0
  metadata_db_path: '/config/.ydl-metadata.db'

ydl_options:
  output: '/youtube-dl/%(title)s [%(id)s]/%(title)s [%(id)s].%(ext)s'
  cache-dir: '/config/.cache'
  embed-sub: True
  write-info-json: False
  check-all-formats: False
  restrict-filenames: True
  sub-lang: en.*
  match-filter: "duration>60 & !is_live & !was_live"
  cookies: '/config/youtube.com_cookies.txt'

profiles:
  youtube-other:
    name: 'Youtube-Other'
    ydl_options:
      output: '/youtube-other/%(title)s [%(id)s].%(ext)s'
      cache-dir: '/config/.cache'
      embed-sub: False
      write-info-json: False
      check-all-formats: False
      restrict-filenames: True
      cookies: '/config/youtube.com_cookies.txt'
```
