### ISSUE TITLE
How do I add --force-ipv4 to the options?

### ISSUE THREAD

**Issue by twist3dimages** [nbr23/youtube-dl-server#115]
Hey, how do I add the command --force-ipv4 to the options?

**Comment by nbr23** [comment]
Hi, in your config.yml, just add `  force-ipv4: true` in the `ydl_options` section.
example:

```yml
ydl_server:   # youtube-dl-server specific settings
  port: 8080      # Port youtube-dl-server should listen on
  host: 0.0.0.0   # IP youtube-dl-server should bind to
  debug: False    # Enable/Disable debug mode
  metadata_db_path: '/youtube-dl/.ydl-metadata.db' # Path to metadata DB
  output_playlist: '/youtube-dl/%(playlist_title)s [%(playlist_id)s]/%(title)s.%(ext)s' # Playlist output directory template
  max_log_entries: 100 # Maximum number of job log history to keep
  forwarded_allow_ips: None # uvicorn Comma seperated list of IPs to trust with proxy headers.
  proxy_headers: True # uvicorn flag Enable/Disable X-Forwarded-Proto, X-Forwarded-For, X-Forwarded-Port to populate remote address info.
  default_format: video/best # Default format selection
  download_workers_count: 2 # Number of download worker threads

ydl_options:  # youtube-dl options
  output: '/youtube-dl/%(title)s [%(id)s].%(ext)s' # output directory template
  cache-dir: '/youtube-dl/.cache' # youtube-dl cache directory
  ignore-errors: True # instruct youtube-dl to skip errors
  age-limit: 6 # minimal age requirement / parental control setting
  force-ipv4: true # IPV4

```
