### ISSUE TITLE
'--add-metadata' option

### ISSUE THREAD

**Issue by Cheezzhead** [nbr23/youtube-dl-server#16]
Is it possible to force the --add-metadata parameter to every initiated download? Using that parameter from the CLI within the container works fine, but I can't find a way to do this from the Web interface.

I think there might be a usable parameter to pass into the YDL_RAW_OPTS dict, but since all youtube-dl repo's are currently taken down due to a DMCA I can't find a complete list of available ydl_opts.

Context: I'm trying to set up a web interface for a friend of mine to download Soundcloud songs, however in order for the audio files to be interpreted properly they need metadata tags.

Thanks in advance!

**Comment by nbr23** [comment]
Hi @Cheezzhead,

Thanks for the issue!
I am looking into making this easier and more generic in the future...

It won't be as easy as setting a raw option (which would be `'addmetadata': True`). When youtube-dl parses the options, it also adds the post processor value: `{'key': 'FFmpegMetadata'}`.

For now I have [dirtily hardcoded](https://github.com/nbr23/youtube-dl-server/commit/856ce81dbdd03a0f3c84862e573b4232a1f05113) this, so just add addmetadata to your YDL_RAW_OPTIONS:

```
app_defaults = {
    'YDL_RAW_OPTIONS': {
        'addmetadata': True,
        },
}
```
Cheers!

**Comment by nbr23** [comment]
Hello,

With the most recent updates, you can just use the config.yml as such:

```yaml
ydl_server:
  port: 8080
  host: 0.0.0.0
  metadata_db_path: '/youtube-dl/.ydl-metadata.db'

ydl_options:
  output: '/youtube-dl/%(title)s [%(id)s].%(ext)s'
  cache-dir: '/youtube-dl/.cache'
  add-metadata: true
```

Cheers!
