### ISSUE TITLE
Changing file ownership after download

### ISSUE THREAD

**Issue by fl0r1s** [nbr23/youtube-dl-server#19]
What is the correct way of running the server as a particular user, so that the files are automatically owned by said user? I am currently running a compose file: 

```
  youtube-dl: 
    image: nbr23/youtube-dl-server:latest
    container_name: youtube-dl
    build: https://github.com/nbr23/youtube-dl-server.git
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - YDL_SERVER_PORT=${YOUTUBE_DL_PORT}
    volumes:
      - ${MEDIA_ROOT}/downloads/youtube-dl:/youtube-dl
    ports: 
      - "${YOUTUBE_DL_PORT}:${YOUTUBE_DL_PORT}"
    restart: unless-stopped
```

But the files are afterwards owned by `root:root`  instead of my user. Additionally, I would like to set all permissions, e.g. by `chmod 777` on the file. 

What is the correct way to achieve this?

**Comment by nbr23** [comment]
Hello @fl0r1s 

For the docker-compose, try using the [`user:`](https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir) key instead of the environment variables.

I see no immediate clean way to set permissions after download. You could probably achieve this with umask or specific acl on the save directory. But hopefully you will not need to chmod 777 once the ownership part is addressed using `user:` in your compose.

Cheers!

**Comment by fl0r1s** [comment]
To anyone that also wants to achieve this: 

Run this once: 
```
  youtube-dl: 
    image: nbr23/youtube-dl-server:latest
    container_name: youtube-dl
    build: https://github.com/nbr23/youtube-dl-server.git
    user: ${PUID}
    environment: 
      - TZ=${TIMEZONE}
      - YDL_SERVER_PORT=${YOUTUBE_DL_PORT}
    volumes:
      - ${MEDIA_ROOT}/downloads/youtube-dl:/youtube-dl
    ports: 
      - "${YOUTUBE_DL_PORT}:${YOUTUBE_DL_PORT}"
    restart: unless-stopped
```
You'll get an error about read/write perms. Follow up by issuing 
```
sudo chown -R ${PUID}:${PGID} ${MEDIA_ROOT}/downloads/youtube-dl
sudo chmod 777 ${MEDIA_ROOT}/downloads/youtube-dl
```
Now your files are owned by user `${PUID}`, but still in group root.

**Comment by fl0r1s** [comment]
Although its really not a nice solution. Is there no better way? Only specifying the `user` parameter does not work, as everything is owned by `root` so you just get permission errors. After a full recreate the database is owned by the user, but the directory is not.

**Comment by nbr23** [comment]
you can do:
```
youtube-dl: 
    image: nbr23/youtube-dl-server:latest
    user: "${PUID}:${PGID}"
    [...]
```
This should help set the group for files created.
