### ISSUE TITLE
cookies option

### ISSUE THREAD

**Issue by rogueralsha** [nbr23/youtube-dl-server#27]
how can I use the youtube-dl or youtube-dlc cookies option with the new config setup?

**Comment by nbr23** [comment]
Hello @rogueralsha,

You can edit your [config.yml](https://github.com/nbr23/youtube-dl-server/blob/master/config.yml) to add in the `ydl_options` section something like:
`cookies: /app_config/cookies.txt`

For example, taking the default config file:
```yaml
ydl_server:   # youtube-dl-server specific settings
  port: 8080      # Port youtube-dl-server should listen on
  host: 0.0.0.0   # IP youtube-dl-server should bind to
  debug: False    # Enable/Disable debug mode
  metadata_db_path: '/youtube-dl/.ydl-metadata.db' # Path to metadata DB
  output_playlist: '/youtube-dl/%(title)s [%(id)s].%(ext)s' # Playlist output directory
  update_poll_delay_min: 1440 # Automatically check for updates every 24h

ydl_options:  # youtube-dl options
  output: '/youtube-dl/%(title)s [%(id)s].%(ext)s' # output directory
  cache-dir: '/youtube-dl/.cache' # youtube-dl cache directory
  ignore-errors: True # instruct youtube-dl to skip errors
  age-limit: 6 # minimal age requirement / parental control setting
  cookies: /app_config/cookies.txt
```
