### ISSUE TITLE
No Downloading of Files

### ISSUE THREAD

**Issue by virse** [nbr23/youtube-dl-server#33]
Hey there,

after the last update YTDL doesn't seem to work anymore.

Whatever URL I try the download won't start. I already reinstalled the docker installation as mentioned in the readme.md

Here are the used config and docker-compose:

config.yml
```
ydl_server:
  port: 8080
  host: 0.0.0.0
  metadata_db_path: '/youtube-dl/.ydl-metadata.db'

ydl_options:
  output: '/youtube-dl/%(title)s.%(ext)s'
  cache-dir: '/youtube-dl/.cache'
```

docker-compose.yml
```
  youtube-dl:
    image: "nbr23/youtube-dl-server:latest"
    container_name: youtubedl
    volumes:
      - $HOME/Docker/youtube-dl:/youtube-dl
      - ./config.yml:/app_config/config.yml:ro # Overwrite the container's config file with your own configuration
    ports:
      - 8888:8080
    restart: unless-stopped
```

I had do chance the part `./config.yml:/usr/src/app/config.yml:ro` to `./config.yml:/app_config/config.yml:ro` otherwise the contaier wouldn't start at all.

The log file of docker shows me

```
today at 15:44  Using configuration file /app_config/config.yml
today at 15:44  Using youtube-dl module
today at 15:44  Started download thread
today at 15:44  Started jobs manager thread
today at 15:44  Updating youtube-dl to the newest version
today at 15:44  Exception in thread Thread-2:
today at 15:44  Traceback (most recent call last):
today at 15:44    File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
today at 15:44      self.run()
today at 15:44    File "/usr/local/lib/python3.9/threading.py", line 892, in run
today at 15:44      self._target(*self._args, **self._kwargs)
today at 15:44    File "/usr/src/app/ydl_server/jobshandler.py", line 33, in worker
today at 15:44      db.clean_old_jobs(self.app_config['ydl_server']
today at 15:44    File "/usr/src/app/ydl_server/logdb.py", line 133, in clean_old_jobs
today at 15:44      oldest = list(cursor.fetchall())[-1][0]
today at 15:44  IndexError: list index out of range
today at 15:44  INFO:     Started server process [1]
today at 15:44  INFO:     Waiting for application startup.
today at 15:44  INFO:     Application startup complete.
today at 15:44  INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
today at 15:44  INFO:     172.17.0.1:40850 - "GET / HTTP/1.1" 200 OK
today at 15:44  INFO:     172.17.0.1:40854 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:44  INFO:     172.17.0.1:40870 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:44  Added url https://www.youtube.com/watch?v=gX_d641zrmM to the download queue
today at 15:44  INFO:     172.17.0.1:40878 - "POST /api/downloads HTTP/1.1" 200 OK
today at 15:44  INFO:     172.17.0.1:40882 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:44  INFO:     172.17.0.1:40908 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:44  INFO:     172.17.0.1:40924 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:44  INFO:     172.17.0.1:40936 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:44  INFO:     172.17.0.1:40952 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:44  INFO:     172.17.0.1:40964 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:45  INFO:     172.17.0.1:40976 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:45  INFO:     172.17.0.1:40998 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:45  INFO:     172.17.0.1:41020 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:45  INFO:     172.17.0.1:41032 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:45  INFO:     172.17.0.1:41048 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:45  INFO:     172.17.0.1:41060 - "GET /finished HTTP/1.1" 200 OK
today at 15:45  INFO:     172.17.0.1:41066 - "GET /api/finished HTTP/1.1" 200 OK
today at 15:45  INFO:     172.17.0.1:41068 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:45  INFO:     172.17.0.1:41076 - "GET /logs HTTP/1.1" 200 OK
today at 15:45  INFO:     172.17.0.1:41082 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:45  INFO:     172.17.0.1:41084 - "GET /api/downloads HTTP/1.1" 200 OK
today at 15:45  INFO:     172.17.0.1:41088 - "GET /index HTTP/1.1" 200 OK
today at 15:45  INFO:     172.17.0.1:41092 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:45  INFO:     172.17.0.1:41108 - "GET /api/downloads/stats HTTP/1.1" 200 OK
today at 15:45  INFO:     172.17.0.1:41136 - "GET /api/downloads/stats HTTP/1.1" 200 OK
```
Any hints on that?

Thx, mike
